# Copyright 2026 ETH Zurich, University of Bologna and Fondazione Chips-IT.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

add_subdirectory(add_fp16_spatz)
add_subdirectory(relu_fp16_spatz)
add_subdirectory(conv2d_fp16_spatz)
add_subdirectory(conv2dgemm_fp16_spatz)
add_subdirectory(gelu_fp16_spatz)
add_subdirectory(gemm_fp16_spatz)
add_subdirectory(globalaveragepool_fp16_spatz)
add_subdirectory(groupnorm_fp16_spatz)
add_subdirectory(group_normalize_fp16_spatz)
add_subdirectory(layernorm_fp16_spatz)
add_subdirectory(matmul_fp16_spatz)
add_subdirectory(maxpool2d_fp16_spatz)
add_subdirectory(mul_fp16_spatz)
add_subdirectory(reducesum_fp16_spatz)
add_subdirectory(sigmoid_fp16_spatz)
add_subdirectory(softmax_fp16_spatz)
add_subdirectory(transpose_fp16_spatz)
add_subdirectory(hello_spatz)
add_subdirectory(fft_fs)
add_subdirectory(onnx_add)
add_subdirectory(onnx_averagepool)
add_subdirectory(onnx_batchnorm)
add_subdirectory(onnx_ceil)
add_subdirectory(onnx_clip)
add_subdirectory(onnx_div)
add_subdirectory(onnx_exp)
add_subdirectory(onnx_floor)
add_subdirectory(onnx_gelu)
add_subdirectory(onnx_gemm)
add_subdirectory(onnx_globalaveragepool)
add_subdirectory(onnx_globalmaxpool)
add_subdirectory(onnx_groupnorm)
add_subdirectory(onnx_hardsigmoid)
add_subdirectory(onnx_hardswish)
add_subdirectory(onnx_instancenorm)
add_subdirectory(onnx_layernorm)
add_subdirectory(onnx_maxpool)
add_subdirectory(onnx_mobilevit_v2)
if(MOBILEVIT_SLICE_DATA)
    add_subdirectory(onnx_mobilevit_slice)
endif()
add_subdirectory(onnx_relu)
add_subdirectory(onnx_resnet18)
add_subdirectory(onnx_sigmoid)
add_subdirectory(onnx_softmax)
add_subdirectory(onnx_sub)
add_subdirectory(onnx_swish)
add_subdirectory(onnx_tinyvit5m)
