# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE.APACHE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Alessandro Nadalini <alessandro.nadalini3@unibo.it>
#         Alberto Dequino <alberto.dequino@unibo.it> 
#         Victor Jung <junvi@iis.ee.ethz.ch>

variables:
  MAGIA: './MAGIA'
  RISCV_GCC_BINROOT: /usr/pack/pulpsdk-1.0-kgf/artifactory/pulp-sdk-release/pkg/pulp_riscv_gcc/1.0.16/bin

stages:
  - clone
  - build
  - run


.python:
  before_script:
    # Cloning MAGIA and recreating Python venv at each job to avoid issues with artifacts
    - make python_ci MAGIA_DIR=$MAGIA

.python_gvsoc:
  before_script:
    - conda create -n magia python=3.12 -y
    - source activate base
    - conda activate magia
    - pip install .

.base:
 artifacts:
  when: always
  expire_in: 4 week


clone-magia:
  extends: .base
  stage: clone
  script:
    - git clone https://github.com/pulp-platform/MAGIA.git
  artifacts:
    paths: [ "MAGIA" ]

clone-gvsoc:
  extends: .base
  stage: clone
  script:
    - make gvsoc_init
  artifacts:
    paths: [ "gvsoc" ]

.gvsoc:
  extends: [.base, .python_gvsoc]
  script:
    - make gvsoc tiles=${tiles}

gvsoc_tiles_2:
  extends: .gvsoc
  stage: build
  needs:
    - job: clone-gvsoc
      artifacts: true
  variables:
    tiles: 2


.MAGIA:
  extends: [.base, .python]
  script:
    - make rtl-clean MAGIA_DIR=$MAGIA
    - source $MAGIA/magia_venv/bin/activate && make MAGIA MAGIA_DIR=$MAGIA tiles=${tiles} target_platform=${target_platform}
  artifacts:
    paths: [ "$MAGIA/work", "$MAGIA/sim/work", "$MAGIA/sim/modelsim.ini", "$MAGIA/scripts/sim_ret_errors.sh", "$MAGIA/scripts/compile.tcl" ]

MAGIA_V2_TILES_2:
  extends: .MAGIA
  stage: build
  needs:
    - job: clone-magia
      artifacts : true
  variables:
    tiles: 2
    target_platform: magia_v2

.export_toolchain:
  before_script:
    - export PATH=$RISCV_GCC_BINROOT:$PATH

.build:
  extends: [.base, .export_toolchain]
  script:
    - make clean build tiles=${tiles} target_platform=${target_platform} compiler=${compiler}
  artifacts:
    paths: [ "build" ]

build_test_magiav2_tiles_2:
  extends: .build
  stage: build
  variables: 
    tiles: 2
    target_platform: magia_v2
    compiler: GCC_PULP

