# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE.APACHE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Alessandro Nadalini <alessandro.nadalini3@unibo.it>
#         Alberto Dequino <alberto.dequino@unibo.it> 
#         Victor Jung <junvi@iis.ee.ethz.ch>

variables:
  MAGIA: './MAGIA'

stages:
  - clone
  - build


.python:
  before_script:
    # Cloning MAGIA and recreating Python venv at each job to avoid issues with artifacts
    - make python_ci MAGIA_DIR=$MAGIA

.base:
 artifacts:
  when: always
  expire_in: 4 week


clone-magia:
  extends: .base
  stage: clone
  script:
    - git clone https://github.com/pulp-platform/MAGIA.git
  artifacts:
    paths: [ "MAGIA" ]


.MAGIA:
  extends: [.base, .python]
  script:
    - make rtl-clean MAGIA_DIR=$MAGIA
    - source $MAGIA/magia_venv/bin/activate && make MAGIA MAGIA_DIR=$MAGIA tiles=${tiles} target_platform=${target_platform}
  artifacts:
    paths: [ "$MAGIA/work", "$MAGIA/sim/work", "$MAGIA/sim/modelsim.ini", "$MAGIA/scripts/sim_ret_errors.sh", "$MAGIA/scripts/compile.tcl" ]

MAGIA_V2_TILES_2:
  extends: .MAGIA
  stage: build
  needs:
    - job: clone-magia
      artifacts : true
  variables:
    tiles: 2
    target_platform: magia_v2


.build:
  extends: .base
  script:
    - make clean build tiles=${tiles} target_platform=${target_platform} compiler=${compiler}
  artifacts:
    paths: [ "build" ]

build_test_magiav2_tiles_2:
  extends: .build
  stage: build
  variables: 
    tiles: 2
    target_platform: magia_v2
    compiler: GCC_PULP