# Copyright (C) 2025 ETH Zurich and University of Bologna
#
# Licensed under the Solderpad Hardware License, Version 0.51
# (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# SPDX-License-Identifier: SHL-0.51
#
# Authors: Victor Isachi <victor.isachi@unibo.it>
# Alberto Dequino <alberto.dequino@unibo.it>
#
# Magia-sdk Makefile

SHELL 			:= /bin/bash

include scripts/deps.env

CURR_DIR		?= $(shell pwd)
CMAKE_BUILDDIR  ?= $(CURR_DIR)/build
MAGIA_RTL_DIR 	?= ..
BUILD_DIR 		?= $(MAGIA_RTL_DIR)/sw/tests/$(test)
MAGIA_DIR_ABS	?= $(abspath $(MAGIA_RTL_DIR))
BUILD_DIR_ABS	?= $(MAGIA_DIR_ABS)/sw/tests/$(test)
GVSOC_DIR 		?= ./gvsoc
GVSOC_ABS_PATH	?= $(CURR_DIR)/gvsoc
BIN_ABS_PATH	?= $(CMAKE_BUILDDIR)/bin
BIN 			?= $(BUILD_DIR)/build/verif
build_mode		?= update
fsync_mode		?= stall
mesh_dv			?= 1
fast_sim		?= 0
eval			?= 0
stalling		?= 1
fsync_mm		?= 1
idma_mm			?= 1
redmule_mm		?= 1
profile_cmp		?= 0
profile_cmi		?= 0
profile_cmo		?= 0
profile_snc		?= 0

# target_platform ?= magia_v2
target_platform ?= magia_v1
compiler 		?= GCC_PULP
# ISA				?= rv32imcxgap9
ISA				?= rv32imac
gui 			?= 0
tiles 			?= 2
spatz			?= 1

LLVM_CMAKE			?= cmake
LLVM_DIR			?= llvm
LLVM_REPO			?= git@github.com:pulp-platform/llvm-project.git
LLVM_COMMIT			?= b494f2d8dde88723026db8ec16ac6c7ee1e140ca
LLVM_INSTALL_DIR	?= $(CURR_DIR)/llvm/install
LLVM_BUILD_DIR		?= $(LLVM_DIR)/llvm-project/build
LLVM_JOBS			?= 8

tiles_2 		:= $(shell echo $$(( $(tiles) * $(tiles) )))
tiles_log    	:= $(shell awk 'BEGIN { printf "%.0f", log($(tiles_2))/log(2) }')
tiles_log_real  := $(shell awk 'BEGIN { printf "%.0f", log($(tiles))/log(2) }')

GVRUN ?= $(GVSOC_DIR)/install/bin/gvrun

CMAKE ?= cmake

GVRUN_COMMON_ARGS ?= --work-dir $(GVSOC_ABS_PATH)/Documents/test --attr magia_v2/n_tiles_x=$(tiles) --attr magia_v2/n_tiles_y=$(tiles) --attr magia_v2/spatz_romfile=$(BIN_ABS_PATH)/bootrom/spatz_init.bin --trace-level=trace --trace=kill-module
GVRUN_ARGS ?= $(GVRUN_COMMON_ARGS) run
GVRUN_PROFILE_ARGS ?= $(GVRUN_COMMON_ARGS) --vcd --event=.* run
profile_tile		?=
PROFILE_TILE_ARG	= $(if $(profile_tile),--trace=tile-$(profile_tile)-idma-ctrl-mm,)

.PHONY: gvsoc build format run_profiling

format:
	@bash scripts/ci/format-changed.sh apply

clean:
	rm -rf build/

rtl-clean:
	cd $(MAGIA_RTL_DIR) 		&& \
	make hw-clean-all
	rm -rf $(MAGIA_RTL_DIR)/sw/tests/test_*

build:
ifeq ($(tiles), )
	$(error tiles is empty!)
endif
	printf '// Auto-generated by `make build tiles=N` -- do not edit by hand.\n// Default: 2x2 mesh. Regenerate with: make build tiles=<N>\n#define MESH_X_TILES %d\n#define MESH_Y_TILES %d\n#define MAX_SYNC_LVL %d\n#define MESH_2_POWER %d\n' $(tiles) $(tiles) $(tiles_log) $(tiles_log_real) > ./targets/$(target_platform)/include/addr_map/tile_config.h
ifeq ($(compiler), LLVM)
	$(error COMING SOON!)
endif
	$(CMAKE) -DTARGET_PLATFORM=$(target_platform) -DTILES=$(tiles) -DEVAL=$(eval) -DSTALLING=$(stalling) -DFSYNC_MM=$(fsync_mm) -DIDMA_MM=$(idma_mm) -DREDMULE_MM=$(redmule_mm) -DCOMPILER=$(compiler) -DPROFILE_CMP=$(profile_cmp) -DPROFILE_CMI=$(profile_cmi) -DPROFILE_CMO=$(profile_cmo) -DPROFILE_SNC=$(profile_snc) -DSPATZ_TESTS=$(spatz) -B $(CMAKE_BUILDDIR) --trace-expand
	$(CMAKE) --build $(CMAKE_BUILDDIR) --verbose

set_mesh:
ifeq ($(tiles), 1)
	$(eval mesh_dv=0)
endif

run: set_mesh
	@echo 'Magia is available at https://github.com/pulp-platform/MAGIA.git'
	@echo 'please run "source setup_env.sh" in the magia folder before running this script'
	@echo 'and make sure the risc-v objdump binary is visible on path using "which riscv32-unknown-elf-objdump".'
ifndef test
	$(error Proper formatting is: make run test=<test_name> platform=rtl|gvsoc)
endif
ifeq (,$(wildcard $(CMAKE_BUILDDIR)/bin/$(test)))
	$(error No test found with name: $(test))
endif
ifndef platform
	$(error Proper formatting is: make run test=<test_name> platform=rtl|gvsoc)
endif
ifeq ($(platform), gvsoc)
	$(GVRUN) --target magia_v2 --param binary=$(BIN_ABS_PATH)/$(test) $(GVRUN_ARGS)
else ifeq ($(platform), rtl)
	mkdir -p $(BUILD_DIR_ABS) && cd $(BUILD_DIR_ABS) && mkdir -p build
	cp ./build/bin/$(test) $(BUILD_DIR_ABS)/build/verif
	objcopy --srec-len 1 --output-target=srec $(BIN) $(BIN).s19
	scripts/parse_s19.pl $(BIN).s19 > $(BIN).txt
	python3 scripts/s19tomem.py $(BIN).txt $(BUILD_DIR_ABS)/build/stim_instr.txt $(BUILD_DIR_ABS)/build/stim_data.txt
	cd $(BUILD_DIR_ABS)													&& \
	cp -sf "$(MAGIA_DIR_ABS)/sim/modelsim.ini" modelsim.ini    			&& \
	ln -sfn "$(MAGIA_DIR_ABS)/sim/work" work
	riscv32-unknown-elf-objdump -d -S -Mmarch=$(ISA) $(BIN) > $(BIN).dump
	riscv32-unknown-elf-objdump -d -l -s -Mmarch=$(ISA) $(BIN) > $(BIN).objdump
	python3 scripts/objdump2itb.py $(BIN).objdump > $(BIN).itb
	cd $(MAGIA_RTL_DIR) 												&& \
	make run test=$(test) gui=$(gui) mesh_dv=$(mesh_dv)
else
	$(error Only rtl and gvsoc are supported as platforms.)
endif

run_profiling: set_mesh
ifndef test
	$(error Proper formatting is: make run_profiling test=<test_name>)
endif
ifeq (,$(wildcard $(CMAKE_BUILDDIR)/bin/$(test)))
	$(error No test found with name: $(test))
endif
	$(GVRUN) --target magia_v2 --param binary=$(BIN_ABS_PATH)/$(test) $(GVRUN_PROFILE_ARGS) $(PROFILE_TILE_ARG)

MAGIA: set_mesh
ifeq ($(shell expr $(tiles_2) \> 256), 1)
	$(eval tiles_2=256)
endif
ifeq ($(target_platform), magia_v1)
	sed -i -E 's/^(num_cores[[:space:]]*\?=[[:space:]]*)[0-9]+/\1$(tiles_2)/' $(MAGIA_RTL_DIR)/Makefile
	sed -i -E 's/^(core[[:space:]]*\?=[[:space:]]*)CV32E40P/\1CV32E40X/' $(MAGIA_RTL_DIR)/Makefile
else ifeq ($(target_platform), magia_v2)
	sed -i -E 's/^(num_cores[[:space:]]*\?=[[:space:]]*)[0-9]+/\1$(tiles_2)/' $(MAGIA_RTL_DIR)/Makefile
	sed -i -E 's/^(core[[:space:]]*\?=[[:space:]]*)CV32E40X/\1CV32E40P/' $(MAGIA_RTL_DIR)/Makefile
else
	$(error unrecognized platform (acceptable platform: magia).)
endif
ifneq ($(tiles), 1)
	sed -i -E 's/^(  localparam int unsigned N_TILES_[XY][[:space:]]*=[[:space:]]*)[0-9]+;/\1$(tiles);/' $(MAGIA_RTL_DIR)/hw/mesh/magia_pkg.sv
endif
ifeq ($(fsync_mode), stall)
	sed -i -E 's/(FSYNC_STALL[[:space:]]=[[:space:]])[0-9]+/\11/' $(MAGIA_RTL_DIR)/hw/tile/magia_tile_pkg.sv
else ifeq ($(fsync_mode), interrupt)
	sed -i -E 's/(FSYNC_STALL[[:space:]]=[[:space:]])[0-9]+/\10/' $(MAGIA_RTL_DIR)/hw/tile/magia_tile_pkg.sv
else
	$(error unrecognized fractal sync mode (acceptable modes: stall|interrupt).)
endif
ifneq (,$(filter $(build_mode), update synth profile))
	cd $(MAGIA_RTL_DIR)														&& \
	make python_venv || true											&& \
	source setup_env.sh 												&& \
	make python_deps || true											&& \
	curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh -s -- --local && \
	export PATH=$$(pwd):$$PATH											&& \
	python -m pip install --upgrade "setuptools<81"						&& \
	make $(build_mode)-ips > $(build_mode)-ips.log mesh_dv=$(mesh_dv)	&& \
	make floonoc-patch || true											&& \
	make build-hw > build-hw.log mesh_dv=$(mesh_dv) fast_sim=$(fast_sim)
else
	$(error unrecognized mode (acceptable build modes: update|profile|synth).)
endif

gvsoc:
ifeq ($(target_platform), magia_v2)
	sed -i -E "s/^[[:space:]]*N_TILES_X[[:space:]]*=[[:space:]]*[0-9]+/    N_TILES_X           = $(tiles)/" $(GVSOC_DIR)/pulp/pulp/chips/magia_v2/arch.py
	sed -i -E "s/^[[:space:]]*N_TILES_Y[[:space:]]*=[[:space:]]*[0-9]+/    N_TILES_Y           = $(tiles)/" $(GVSOC_DIR)/pulp/pulp/chips/magia_v2/arch.py
else
	$(error unrecognized platform (acceptable platform: magia_v2).)
endif
ifeq ($(spatz), 1)
	sed -i 's/^\([[:space:]]*SPATZ_ENABLE[[:space:]]*=[[:space:]]*\)False/\1True/' $(GVSOC_DIR)/pulp/pulp/chips/magia_v2/arch.py
else
	sed -i 's/^\([[:space:]]*SPATZ_ENABLE[[:space:]]*=[[:space:]]*\)True/\1False/' "$(GVSOC_DIR)/pulp/pulp/chips/magia_v2/arch.py"
endif
	cd $(GVSOC_DIR)	&& \
	make build TARGETS=magia_v2

# Pinned commits for FondazioneChipsIT/gvsoc, gvsoc-core, pulp, engine, gvrun live in scripts/deps.env.
gvsoc_init:
	git clone https://github.com/FondazioneChipsIT/gvsoc.git || true
	cd $(GVSOC_DIR) && \
	git fetch origin $(GVSOC_COMMIT) && \
	git checkout $(GVSOC_COMMIT) && \
	git submodule update --init --recursive && \
	cd core && \
	git fetch origin $(GVSOC_CORE_COMMIT) && \
	git checkout $(GVSOC_CORE_COMMIT) && \
	cd ../pulp && \
	git fetch origin $(GVSOC_PULP_COMMIT) && \
	git checkout $(GVSOC_PULP_COMMIT) && \
	cd ../engine && \
	git fetch origin $(GVSOC_ENGINE_COMMIT) && \
	git checkout $(GVSOC_ENGINE_COMMIT) && \
	cd ../gvrun && \
	git fetch origin $(GVSOC_GVRUN_COMMIT) && \
	git checkout $(GVSOC_GVRUN_COMMIT)

gvsoc_venv:
	eval "$(pyenv init -)" && \
	pyenv local 3.12 && \
	python -m venv gvsoc_venv && \
	source gvsoc_venv/bin/activate && \
	pip install .

llvm:
	mkdir -p $(LLVM_DIR)
	if [ ! -d "$(LLVM_DIR)/llvm-project/.git" ]; then \
		cd $(LLVM_DIR) && git clone $(LLVM_REPO); \
	fi
	cd $(LLVM_DIR)/llvm-project && \
	git checkout $(LLVM_COMMIT) && \
	git submodule update --init --recursive --jobs=$(LLVM_JOBS) .
	mkdir -p $(LLVM_INSTALL_DIR)
	cd $(LLVM_DIR)/llvm-project && mkdir -p build && cd build && \
	$(LLVM_CMAKE) \
		-DCMAKE_INSTALL_PREFIX=$(LLVM_INSTALL_DIR) \
		-DCMAKE_CXX_COMPILER=${CXX} \
		-DCMAKE_C_COMPILER=${CC} \
		-DLLVM_OPTIMIZED_TABLEGEN=True \
		-DLLVM_ENABLE_PROJECTS="clang;lld" \
		-DLLVM_TARGETS_TO_BUILD="RISCV" \
		-DLLVM_DEFAULT_TARGET_TRIPLE=riscv32-unknown-elf \
		-DLLVM_ENABLE_LLD=False \
		-DLLVM_APPEND_VC_REV=ON \
		-DCMAKE_BUILD_TYPE=Release \
		../llvm && \
	make -j$(LLVM_JOBS) all && \
	make install
