#ifndef MOBILEVIT_SLICE_CONFIG_H_
#define MOBILEVIT_SLICE_CONFIG_H_

#define SLICE_ELEMENTS (8192u)
#define SLICE_BYTES (SLICE_ELEMENTS * 2u)
#define SLICE_ATOL (0.5f)
#define SLICE_RTOL (0.05f)
#define SLICE_INPUTS_OFFSET (0u)
#define SLICE_REFERENCES_OFFSET (MOBILEVIT_SLICE_TOKENS * SLICE_BYTES)
#define SLICE_GN_SCALE_OFFSET (SLICE_REFERENCES_OFFSET + MOBILEVIT_SLICE_TOKENS * SLICE_BYTES)
#define SLICE_GN_BIAS_OFFSET (SLICE_GN_SCALE_OFFSET + 256u)
#define SLICE_QKV_WEIGHT_OFFSET (SLICE_GN_BIAS_OFFSET + 256u)
#define SLICE_QKV_BIAS_OFFSET (SLICE_QKV_WEIGHT_OFFSET + 65792u)
#define SLICE_OUT_WEIGHT_OFFSET (SLICE_QKV_BIAS_OFFSET + 514u)
#define SLICE_OUT_BIAS_OFFSET (SLICE_OUT_WEIGHT_OFFSET + 32768u)

#endif
