// Copyright 2026 ETH Zurich, University of Bologna and Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Francesco Conti <f.conti@unibo.it>
//
// Generated by mgc from mm_ws.mgc: do not edit, re-run mgc/mgcc.py.

#include <stdint.h>
#include "test.h"

#include "tile.h"
#include "fsync.h"
#include "mg_idma.h"
#include "mg_redmule.h"
#include "mg_event.h"

#define N_ITERATIONS 1
#define WAIT_MODE    WFE

/**
 * This test aims to verify the functionality of MAGIA as a systolic array for matrix
 * multiplications, following the weight-static mechanism. Each tile keeps a block of W in
 * L1; blocks of output rows flow down the mesh columns, accumulating x @ w at each tile.
 */
int main(void)
{
    /**
     * 0. Get the mesh-tile's hartid, mesh-tile coordinates and define its L1 base,
     * also initialize the controllers for the idma, redmule and fsync
     */
    uint32_t hartid = get_hartid();

    idma_config_t idma_cfg      = {.hartid = hartid};
    idma_controller_t idma_ctrl = {
        .base = NULL,
        .cfg  = &idma_cfg,
        .api  = &idma_api,
    };

    redmule_config_t redmule_cfg      = {.hartid = hartid};
    redmule_controller_t redmule_ctrl = {
        .base = NULL,
        .cfg  = &redmule_cfg,
        .api  = &redmule_api,
    };

    fsync_config_t fsync_cfg      = {.hartid = hartid};
    fsync_controller_t fsync_ctrl = {
        .base = NULL,
        .cfg  = &fsync_cfg,
        .api  = &fsync_api,
    };

    fsync_init(&fsync_ctrl);
    idma_init(&idma_ctrl);
    redmule_init(&redmule_ctrl);

    eu_config_t eu_cfg      = {.hartid = hartid};
    eu_controller_t eu_ctrl = {
        .base = NULL,
        .cfg  = &eu_cfg,
        .api  = &eu_api,
    };
    eu_init(&eu_ctrl);
    eu_redmule_init(&eu_ctrl, 0);
    eu_idma_init(&eu_ctrl, 0);
    eu_fsync_init(&eu_ctrl, 0);

    uint32_t y_id         = GET_Y_ID(hartid);
    uint32_t x_id         = GET_X_ID(hartid);
    uint32_t l1_tile_base = get_l1_base(hartid);

    /**
     * 1. Static weight data-tile: N is split over the mesh rows, K over the mesh columns.
     */
    uint32_t tile_h_max = ((N_SIZE + MESH_Y_TILES - 1) / MESH_Y_TILES);
    uint32_t tile_w_max = ((K_SIZE + MESH_X_TILES - 1) / MESH_X_TILES);
    int32_t tile_h;
    int32_t tile_w;

    if (((tile_h_max * y_id) + tile_h_max) > N_SIZE) {
        tile_h = N_SIZE - (tile_h_max * y_id);
    } else {
        tile_h = tile_h_max;
    }

    if (((tile_w_max * x_id) + tile_w_max) > K_SIZE) {
        tile_w = K_SIZE - (tile_w_max * x_id);
    } else {
        tile_w = tile_w_max;
    }

    if (tile_h < 1 || tile_w < 1) {
        return 0;
    }

    /**
     * 1a. The M dimension is processed in timeslots. Row y_id of the mesh starts 2 time
     * steps after the row above it (a block takes one step to compute, one to travel down).
     */
    uint8_t timeslots       = 4;
    uint8_t t_size          = M_SIZE / timeslots;
    uint8_t t_start         = y_id * 2;
    uint8_t total_timeslots = (MESH_Y_TILES - 1) * 2 + timeslots + 1;

    /**
     * 2. L1 buffers: the static weights, and multi-buffers for the input and output blocks.
     */
    uint32_t len_w      = tile_w * 2;
    uint32_t std_w      = K_SIZE * 2;
    uint32_t reps_w     = (uint32_t)tile_h;
    uint32_t obi_addr_w = (l1_tile_base);
    uint32_t axi_addr_w =
        (uint32_t)w_inp + (tile_h_max * y_id * K_SIZE * 2) + (tile_w_max * x_id * 2);
    uint32_t len_x        = tile_h * 2;
    uint32_t std_x        = N_SIZE * 2;
    uint32_t reps_x       = (uint32_t)t_size;
    uint32_t obi_addr_x_0 = obi_addr_w + (tile_h_max * tile_w_max * 2);
    uint32_t obi_addr_x_1 = obi_addr_x_0 + (t_size * tile_h_max * 2);
    uint32_t axi_addr_x   = (uint32_t)x_inp + (tile_h_max * y_id * 2);
    uint32_t len_y        = tile_w * 2;
    uint32_t std_y        = K_SIZE * 2;
    uint32_t reps_y       = (uint32_t)t_size;
    uint32_t obi_addr_y_0 = obi_addr_x_1 + (t_size * tile_h_max * 2);
    uint32_t obi_addr_y_1 = obi_addr_y_0 + (t_size * tile_w_max * 2);
    uint32_t obi_addr_y_2 = obi_addr_y_1 + (t_size * tile_w_max * 2);
    uint32_t axi_addr_y   = (uint32_t)y_inp + (tile_w_max * x_id * 2);

    volatile uint32_t x_pt;
    volatile uint32_t y_pt;
    volatile uint32_t y_pt_prev;
    volatile uint32_t x_pt_next;
    volatile uint32_t y_pt_next;

    mg_event_t idma_evt_w, idma_evt_x, idma_evt_y_in, idma_evt_y_out;
    mg_event_t redmule_evt;
    uint32_t l1_base_s = get_l1_base(hartid + MESH_X_TILES);

    /**
     * TEST LOOP - REPEAT THE TEST N_ITERATION TIMES.
     */
    for (int z = 0; z < N_ITERATIONS; z++) {
        mg_idma_memcpy_2d(&idma_ctrl,
                          &eu_ctrl,
                          WAIT_MODE,
                          0,
                          axi_addr_w,
                          obi_addr_w,
                          len_w,
                          std_w,
                          reps_w,
                          &idma_evt_w,
                          NULL);
        mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_w);

        /**
         * 3. Systolic pipeline over the output blocks: load the input block (and, on the top
         * row, the bias block), accumulate, then pass the block to the tile below (the bottom
         * row stores it to L2). A global barrier closes every time step.
         */
        if (y_id == 0) {
            mg_idma_memcpy_2d(&idma_ctrl,
                              &eu_ctrl,
                              WAIT_MODE,
                              0,
                              axi_addr_y,
                              obi_addr_y_0,
                              len_y,
                              std_y,
                              reps_y,
                              &idma_evt_y_in,
                              NULL);
        }

        mg_idma_memcpy_2d(&idma_ctrl,
                          &eu_ctrl,
                          WAIT_MODE,
                          0,
                          axi_addr_x,
                          obi_addr_x_0,
                          len_x,
                          std_x,
                          reps_x,
                          &idma_evt_x,
                          NULL);

        if (y_id == 0) {
            mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_y_in);
        }
        mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_x);
        fsync_sync_global(&fsync_ctrl);
        eu_fsync_wait(&eu_ctrl, WAIT_MODE);

        for (int t = 0; t < total_timeslots; t++) {
            int pt = t - t_start;

            if (pt >= 0 && pt <= timeslots) {
                if (pt % 2) {
                    x_pt      = obi_addr_x_1;
                    x_pt_next = obi_addr_x_0;
                } else {
                    x_pt      = obi_addr_x_0;
                    x_pt_next = obi_addr_x_1;
                }

                switch (pt % 3) {
                case 0:
                    y_pt      = obi_addr_y_0;
                    y_pt_prev = obi_addr_y_2;
                    y_pt_next = obi_addr_y_1;
                    break;
                case 1:
                    y_pt      = obi_addr_y_1;
                    y_pt_prev = obi_addr_y_0;
                    y_pt_next = obi_addr_y_2;
                    break;
                case 2:
                    y_pt      = obi_addr_y_2;
                    y_pt_prev = obi_addr_y_1;
                    y_pt_next = obi_addr_y_0;
                    break;
                }

                if (pt < (timeslots - 1)) {
                    if (y_id == 0) {
                        mg_idma_memcpy_2d(&idma_ctrl,
                                          &eu_ctrl,
                                          WAIT_MODE,
                                          0,
                                          axi_addr_y + ((pt + 1) * t_size * K_SIZE * 2),
                                          y_pt_next,
                                          len_y,
                                          std_y,
                                          reps_y,
                                          &idma_evt_y_in,
                                          NULL);
                    }

                    mg_idma_memcpy_2d(&idma_ctrl,
                                      &eu_ctrl,
                                      WAIT_MODE,
                                      0,
                                      axi_addr_x + ((pt + 1) * t_size * N_SIZE * 2),
                                      x_pt_next,
                                      len_x,
                                      std_x,
                                      reps_x,
                                      &idma_evt_x,
                                      NULL);
                }

                if (pt > 0) {
                    if (y_id == (MESH_Y_TILES - 1)) {
                        mg_idma_memcpy_2d(&idma_ctrl,
                                          &eu_ctrl,
                                          WAIT_MODE,
                                          1,
                                          axi_addr_y + ((pt - 1) * t_size * K_SIZE * 2),
                                          y_pt_prev,
                                          len_y,
                                          std_y,
                                          reps_y,
                                          &idma_evt_y_out,
                                          NULL);
                    } else {
                        mg_idma_memcpy_1d(&idma_ctrl,
                                          &eu_ctrl,
                                          WAIT_MODE,
                                          1,
                                          l1_base_s + (y_pt_prev - l1_tile_base),
                                          y_pt_prev,
                                          t_size * tile_w * 2,
                                          &idma_evt_y_out,
                                          NULL);
                    }
                }

                if (pt < timeslots) {
                    mg_redmule_gemm(&redmule_ctrl,
                                    &eu_ctrl,
                                    WAIT_MODE,
                                    x_pt,
                                    obi_addr_w,
                                    y_pt,
                                    (uint16_t)t_size,
                                    (uint16_t)tile_h,
                                    (uint16_t)tile_w,
                                    &redmule_evt,
                                    NULL);
                }

                if (pt < (timeslots - 1)) {
                    if (y_id == 0) {
                        mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_y_in);
                    }
                    mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_x);
                }

                if (pt > 0) {
                    mg_idma_wait(&eu_ctrl, 1, WAIT_MODE, &idma_evt_y_out);
                }

                if (pt < timeslots) {
                    mg_redmule_wait(&eu_ctrl, WAIT_MODE, &redmule_evt);
                }
            }
            fsync_sync_global(&fsync_ctrl);
            eu_fsync_wait(&eu_ctrl, WAIT_MODE);
        }
    }

    /**
     * 4. Check results
     */
    fsync_sync_col(&fsync_ctrl);
    eu_fsync_wait(&eu_ctrl, WAIT_MODE);
    uint32_t errors = 0;

    if (y_id == (MESH_Y_TILES - 1)) {
        uint16_t computed, expected, diff = 0;
        for (int i = 0; i < M_SIZE; i++) {
            for (int j = (tile_w_max * x_id); j < (tile_w_max * x_id + tile_w); j++) {
                computed = *(volatile uint16_t *)(y_inp + (i * K_SIZE + j));
                expected = *(volatile uint16_t *)(z_out + (i * K_SIZE + j));
                diff     = (computed > expected) ? (computed - expected) : (expected - computed);
                if (diff > 0x0011) {
#if EVAL == 1
                    printf("Error detected at coordinates[%d][%d]: Y=%x Z=%x\n",
                           i,
                           j,
                           *(volatile uint16_t *)(y_inp + (i * K_SIZE + j)),
                           *(volatile uint16_t *)(z_out + (i * K_SIZE + j)));
#endif
                    errors++;
                }
            }
        }
        printf("TILE %d: Number of errors: %d\n", hartid, errors);
    }

    return errors;
}
