// Copyright 2026 ETH Zurich, University of Bologna and Fondazione Chips-IT.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Francesco Conti <f.conti@unibo.it>
//
// Generated by mgc from mm_os_l1k.mgc: do not edit, re-run mgc/mgcc.py.

#include <stdint.h>
#include "test.h"

#include "tile.h"
#include "mg_idma.h"
#include "mg_redmule.h"
#include "mg_event.h"

#define N_TIMESLOTS 8
#define WAIT_MODE   WFE

/** L1 kernel (CORE): all pointers are L1 addresses. */
extern void l1_copy_fp16(uint32_t dst, uint32_t src, uint32_t p0);

/**
 * Output-static GEMM on MAGIA with a software L1 kernel on the input path:
 * X block --iDMA--> x_raw --CV32 kernel--> x --RedMulE--> y (+= x @ w).
 */
int main(void)
{
    /**
     * 0. Get the mesh-tile's hartid, mesh-tile coordinates and define its L1 base,
     * also initialize the controllers for the idma and redmule.
     */
    uint32_t hartid = get_hartid();

    idma_config_t idma_cfg      = {.hartid = hartid};
    idma_controller_t idma_ctrl = {
        .base = NULL,
        .cfg  = &idma_cfg,
        .api  = &idma_api,
    };

    redmule_config_t redmule_cfg      = {.hartid = hartid};
    redmule_controller_t redmule_ctrl = {
        .base = NULL,
        .cfg  = &redmule_cfg,
        .api  = &redmule_api,
    };

    idma_init(&idma_ctrl);
    redmule_init(&redmule_ctrl);

    eu_config_t eu_cfg      = {.hartid = hartid};
    eu_controller_t eu_ctrl = {
        .base = NULL,
        .cfg  = &eu_cfg,
        .api  = &eu_api,
    };
    eu_init(&eu_ctrl);
    eu_redmule_init(&eu_ctrl, 0);
    eu_idma_init(&eu_ctrl, 0);

    uint32_t y_id         = GET_Y_ID(hartid);
    uint32_t x_id         = GET_X_ID(hartid);
    uint32_t l1_tile_base = get_l1_base(hartid);

    uint32_t tile_h_max = ((M_SIZE + MESH_Y_TILES - 1) / MESH_Y_TILES);
    uint32_t tile_w_max = ((K_SIZE + MESH_X_TILES - 1) / MESH_X_TILES);
    int32_t tile_h;
    int32_t tile_w;

    if (((tile_h_max * y_id) + tile_h_max) > M_SIZE) {
        tile_h = M_SIZE - (tile_h_max * y_id);
    } else {
        tile_h = tile_h_max;
    }

    if (((tile_w_max * x_id) + tile_w_max) > K_SIZE) {
        tile_w = K_SIZE - (tile_w_max * x_id);
    } else {
        tile_w = tile_w_max;
    }

    if (tile_h < 1 || tile_w < 1) {
        return 0;
    }
    uint8_t timeslots  = N_TIMESLOTS;
    uint8_t t_size     = N_SIZE / timeslots;
    uint32_t len_y     = tile_w * 2;
    uint32_t std_y     = K_SIZE * 2;
    uint32_t reps_y    = (uint32_t)tile_h;
    uint32_t l1_addr_y = (l1_tile_base);
    uint32_t l2_addr_y =
        (uint32_t)y_inp + (tile_h_max * y_id * K_SIZE * 2) + (tile_w_max * x_id * 2);
    uint32_t len_x_raw       = t_size * 2;
    uint32_t std_x_raw       = N_SIZE * 2;
    uint32_t reps_x_raw      = (uint32_t)tile_h;
    uint32_t l1_addr_x_raw_0 = l1_addr_y + (tile_h * tile_w * 2);
    uint32_t l1_addr_x_raw_1 = l1_addr_x_raw_0 + (tile_h * t_size * 2);
    uint32_t l2_addr_x_raw   = (uint32_t)x_inp + (tile_h_max * y_id * N_SIZE * 2);
    uint32_t len_x           = t_size * 2;
    uint32_t std_x           = N_SIZE * 2;
    uint32_t reps_x          = (uint32_t)tile_h;
    uint32_t l1_addr_x_0     = l1_addr_x_raw_1 + (tile_h * t_size * 2);
    uint32_t l1_addr_x_1     = l1_addr_x_0 + (tile_h * t_size * 2);
    uint32_t l2_addr_x       = (uint32_t)x_inp + (tile_h_max * y_id * N_SIZE * 2);
    uint32_t len_w           = tile_w * 2;
    uint32_t std_w           = K_SIZE * 2;
    uint32_t reps_w          = (uint32_t)t_size;
    uint32_t l1_addr_w_0     = l1_addr_x_1 + (tile_h * t_size * 2);
    uint32_t l1_addr_w_1     = l1_addr_w_0 + (t_size * tile_w * 2);
    uint32_t l1_addr_w_2     = l1_addr_w_1 + (t_size * tile_w * 2);
    uint32_t l2_addr_w       = (uint32_t)w_inp + (tile_w_max * x_id * 2);

    volatile uint32_t x_raw_pt;
    volatile uint32_t x_pt;
    volatile uint32_t w_pt;
    volatile uint32_t x_pt_prev;
    volatile uint32_t w_pt_prev;
    volatile uint32_t x_raw_pt_next;
    volatile uint32_t w_pt_next;

    mg_event_t idma_evt_y, idma_evt_x_raw, idma_evt_w;
    mg_event_t redmule_evt;

    mg_idma_memcpy_2d(&idma_ctrl,
                      &eu_ctrl,
                      WAIT_MODE,
                      0,
                      l2_addr_y,
                      l1_addr_y,
                      len_y,
                      std_y,
                      reps_y,
                      &idma_evt_y,
                      NULL);
    mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_y);

    mg_idma_memcpy_2d(&idma_ctrl,
                      &eu_ctrl,
                      WAIT_MODE,
                      0,
                      l2_addr_x_raw,
                      l1_addr_x_raw_0,
                      len_x_raw,
                      std_x_raw,
                      reps_x_raw,
                      &idma_evt_x_raw,
                      NULL);

    mg_idma_memcpy_2d(&idma_ctrl,
                      &eu_ctrl,
                      WAIT_MODE,
                      0,
                      l2_addr_w,
                      l1_addr_w_0,
                      len_w,
                      std_w,
                      reps_w,
                      &idma_evt_w,
                      NULL);
    mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_x_raw);
    mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_w);

    for (int i = 0; i < timeslots + 1; i++) {
        if (i % 2) {
            x_raw_pt      = l1_addr_x_raw_1;
            x_raw_pt_next = l1_addr_x_raw_0;
            x_pt          = l1_addr_x_1;
            x_pt_prev     = l1_addr_x_0;
        } else {
            x_raw_pt      = l1_addr_x_raw_0;
            x_raw_pt_next = l1_addr_x_raw_1;
            x_pt          = l1_addr_x_0;
            x_pt_prev     = l1_addr_x_1;
        }

        switch (i % 3) {
        case 0:
            w_pt      = l1_addr_w_0;
            w_pt_prev = l1_addr_w_2;
            w_pt_next = l1_addr_w_1;
            break;
        case 1:
            w_pt      = l1_addr_w_1;
            w_pt_prev = l1_addr_w_0;
            w_pt_next = l1_addr_w_2;
            break;
        case 2:
            w_pt      = l1_addr_w_2;
            w_pt_prev = l1_addr_w_1;
            w_pt_next = l1_addr_w_0;
            break;
        }

        if (i < (timeslots - 1)) {
            mg_idma_memcpy_2d(&idma_ctrl,
                              &eu_ctrl,
                              WAIT_MODE,
                              0,
                              l2_addr_x_raw + ((i + 1) * t_size * 2),
                              x_raw_pt_next,
                              len_x_raw,
                              std_x_raw,
                              reps_x_raw,
                              &idma_evt_x_raw,
                              NULL);

            mg_idma_memcpy_2d(&idma_ctrl,
                              &eu_ctrl,
                              WAIT_MODE,
                              0,
                              l2_addr_w + ((i + 1) * t_size * K_SIZE * 2),
                              w_pt_next,
                              len_w,
                              std_w,
                              reps_w,
                              &idma_evt_w,
                              NULL);
        }

        if (i > 0) {
            mg_redmule_gemm(&redmule_ctrl,
                            &eu_ctrl,
                            WAIT_MODE,
                            x_pt_prev,
                            w_pt_prev,
                            l1_addr_y,
                            (uint16_t)tile_h,
                            (uint16_t)t_size,
                            (uint16_t)tile_w,
                            &redmule_evt,
                            NULL);
        }

        if (i < timeslots) {
            l1_copy_fp16(x_pt, x_raw_pt, tile_h * t_size);
        }

        if (i < (timeslots - 1)) {
            mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_x_raw);
            mg_idma_wait(&eu_ctrl, 0, WAIT_MODE, &idma_evt_w);
        }

        if (i > 0) {
            mg_redmule_wait(&eu_ctrl, WAIT_MODE, &redmule_evt);
        }
    }

    mg_idma_memcpy_2d(&idma_ctrl,
                      &eu_ctrl,
                      WAIT_MODE,
                      1,
                      l2_addr_y,
                      l1_addr_y,
                      len_y,
                      std_y,
                      reps_y,
                      &idma_evt_y,
                      NULL);
    mg_idma_wait(&eu_ctrl, 1, WAIT_MODE, &idma_evt_y);
    uint32_t errors = 0;
    uint16_t computed, expected, diff = 0;
    for (int i = (tile_h_max * y_id); i < (tile_h_max * y_id + tile_h); i++) {
        for (int j = (tile_w_max * x_id); j < (tile_w_max * x_id + tile_w); j++) {
            computed = *(volatile uint16_t *)(y_inp + (i * K_SIZE + j));
            expected = *(volatile uint16_t *)(z_out + (i * K_SIZE + j));
            diff     = (computed > expected) ? (computed - expected) : (expected - computed);
            if (diff > 0x0011) {
#if EVAL == 1
                printf("Error detected at coordinates[%d][%d]: Y=%x Z=%x\n",
                       i,
                       j,
                       *(volatile uint16_t *)(y_inp + (i * K_SIZE + j)),
                       *(volatile uint16_t *)(z_out + (i * K_SIZE + j)));
#endif
                errors++;
            }
        }
    }
    printf("TILE %d: Number of errors: %d\n", hartid, errors);

    return errors;
}
