# Copyright 2026 ETH Zurich, University of Bologna and Fondazione Chips-IT.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Francesco Conti <f.conti@unibo.it>
"""mgc compiler tests: mgc/.venv/bin/python -m unittest discover -s mgc/tests"""

import os
import shutil
import subprocess
import sys
import unittest
from unittest import mock

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.dirname(HERE))

from mgc import devices  # noqa: E402
from mgc.driver import compile_module, compile_source, print_ir  # noqa: E402
from mgc.errors import MgcError  # noqa: E402

MESH = os.path.join(REPO, 'tests', 'magia', 'mesh')
OS, WS, IS, L1K = (os.path.join(MESH, d) for d in ('mm_os_mgc', 'mm_ws_mgc', 'mm_is_mgc', 'mm_os_l1k'))


def _read(d, name):
    with open(os.path.join(d, name)) as f:
        return f.read()


def _hdr(d):
    return os.path.join(d, 'include', 'test.h')


def _c(d, name, src=None):
    return compile_source(src if src is not None else _read(d, name), name, _hdr(d))


def _body(c):
    # drop the banner line naming the source file
    return '\n'.join(l for l in c.splitlines() if not l.startswith('// Generated by mgc'))


def _clang_format():
    for p in (shutil.which('clang-format'), os.path.join(REPO, 'llvm', 'install', 'bin', 'clang-format')):
        if p and os.access(p, os.X_OK):
            return p
    return None


class Golden(unittest.TestCase):
    """The committed tests are exactly what mgcc produces from their sources."""

    def check(self, d, name):
        if _clang_format() is None:
            self.skipTest('clang-format not available')
        out = subprocess.run([sys.executable, os.path.join(REPO, 'mgc', 'mgcc.py'), os.path.join(d, name)],
                             capture_output=True, text=True, check=True).stdout
        self.assertEqual(out, _read(d, os.path.join('src', 'test.c')))

    def test_mm_os(self):
        self.check(OS, 'mm_os.mgc')

    def test_mm_ws(self):
        self.check(WS, 'mm_ws.mgc')

    def test_mm_is(self):
        self.check(IS, 'mm_is.mgc')

    def test_mm_os_l1k(self):
        self.check(L1K, 'mm_os_l1k.mgc')


class Equivalence(unittest.TestCase):

    def test_os_pipelined_equals_explicit(self):
        self.assertEqual(_body(_c(OS, 'mm_os.mgc')), _body(_c(OS, 'mm_os_explicit.mgc')))

    def test_os_schedule_order(self):
        c = _c(OS, 'mm_os.mgc')
        loop = c[c.index('if (i < (timeslots - 1))'):]
        order = [k for k in ('mg_redmule_gemm_start', 'axi_addr_x +', 'mg_redmule_gemm_enqueue',
                             'axi_addr_w +', '&idma_evt_x);', '&idma_evt_w);',
                             'mg_redmule_gemm_commit_start', 'redmule_evt_curr);')]
        self.assertEqual(order, sorted(order, key=loop.index))
        # the hand-written shape: the current-job wait is in both branches
        self.assertEqual(loop.count('mg_redmule_wait(&eu_ctrl, WAIT_MODE, redmule_evt_curr);'), 2)

    def test_ir_after_pipeline_has_no_pipeline(self):
        ir = print_ir(compile_module(_read(WS, 'mm_ws.mgc'), 'mm_ws.mgc', _hdr(WS), until='pipeline'))
        self.assertNotIn('mg.pipeline', ir)
        self.assertIn('mg.job', ir)  # in-step jobs are lowered later, by job-lower


class Systolic(unittest.TestCase):

    def test_ws_stages_and_guards(self):
        c = _c(WS, 'mm_ws.mgc')
        self.assertIn('int32_t pt = t - t_start;', c)
        self.assertIn('if (pt >= 0 && pt <= timeslots) {', c)
        for g in ('if (pt < (timeslots - 1)) {', 'if (pt > 0) {', 'if (pt < timeslots) {'):
            self.assertIn(g, c)
        # jobs reading data sent by a neighbour run within their step (no early enqueue)
        self.assertIn('mg_redmule_gemm(&redmule_ctrl', c)
        self.assertNotIn('mg_redmule_gemm_enqueue', c)
        self.assertEqual(c.count('fsync_sync_global(&fsync_ctrl);'), 2)  # prologue + every step

    def test_remote_store_and_uniform_layout(self):
        c = _c(WS, 'mm_ws.mgc')
        self.assertIn('uint32_t l1_base_s = get_l1_base(hartid + MESH_X_TILES);', c)
        self.assertIn('l1_base_s + (y_pt_prev - l1_tile_base),', c)
        # every tile must lay out L1 identically: worst-case (max) tile sizes
        self.assertIn('obi_addr_x_0 = obi_addr_w + (tile_h_max * tile_w_max * 2);', c)
        # ...whereas without neighbour access the actual sizes are used (as in mm_os)
        self.assertIn('obi_addr_x_0 = obi_addr_y + (tile_h * tile_w * 2);', _c(OS, 'mm_os.mgc'))

    def test_is_east_and_row_barrier(self):
        c = _c(IS, 'mm_is.mgc')
        self.assertIn('uint32_t l1_base_e = get_l1_base(hartid + 1);', c)
        self.assertIn('fsync_sync_row(&fsync_ctrl);', c)
        self.assertNotIn('fsync_sync_global', c)

    def test_event_storage_split_only_when_overlapping(self):
        ws = _c(WS, 'mm_ws.mgc')  # y is loaded (top row) while the previous block is sent
        self.assertIn('idma_evt_y_in', ws)
        self.assertIn('idma_evt_y_out', ws)
        os_ = _c(OS, 'mm_os.mgc')  # y load and store never overlap
        self.assertIn('mg_event_t idma_evt_y, idma_evt_x, idma_evt_w;', os_)

    def test_explicit_ws_compiles_with_rotate_and_continue(self):
        c = _c(WS, 'mm_ws_explicit.mgc')
        i, j = c.index('3b. Select'), c.index('switch (pt % 3)')
        self.assertLess(i, j)
        self.assertIn('continue;', c)

    def test_depth_too_small(self):
        src = _read(WS, 'mm_ws.mgc').replace('Y[0:t_size, tile_w], depth=3', 'Y[0:t_size, tile_w], depth=2')
        with self.assertRaises(MgcError) as cm:
            _c(WS, 'x.mgc', src)
        self.assertIn('live across 3 pipeline stages', str(cm.exception))


class Kernels(unittest.TestCase):

    def test_core_call_and_prototype(self):
        c = _c(L1K, 'mm_os_l1k.mgc')
        self.assertIn('extern void l1_copy_fp16(uint32_t dst, uint32_t src, uint32_t p0);', c)
        self.assertIn('l1_copy_fp16(x_pt, x_raw_pt, tile_h * t_size);', c)

    def test_async_job_issued_before_sync_call(self):
        c = _c(L1K, 'mm_os_l1k.mgc')
        self.assertLess(c.index('mg_redmule_gemm(&redmule_ctrl'), c.index('l1_copy_fp16(x_pt'))

    def test_kernel_operand_count(self):
        src = _read(L1K, 'mm_os_l1k.mgc').replace('copy(x[i], x_raw[i])', 'copy(x[i])')
        with self.assertRaises(MgcError) as cm:
            _c(L1K, 'x.mgc', src)
        self.assertIn('takes 2 L1 operands', str(cm.exception))

    def test_kernel_operands_must_be_l1(self):
        src = _read(L1K, 'mm_os_l1k.mgc').replace('copy(x[i], x_raw[i])', 'copy(x[i], X[tile_h, 0:t_size])')
        with self.assertRaises(MgcError) as cm:
            _c(L1K, 'x.mgc', src)
        self.assertIn('expected an L1 buffer', str(cm.exception))


class Extensibility(unittest.TestCase):
    """New iDMA modes and new HWPEs are descriptor changes only."""

    X3 = ('X3 = l2("x_inp", (M, 4, N // 4), fp16)\nZ = l2(', '        redmule_evt = redmule.events(2)')

    def _x3(self, alloc):
        s = _read(OS, 'mm_os_explicit.mgc').replace('Z = l2(', self.X3[0], 1).replace(
            self.X3[1], self.X3[1] + '\n        q = L1.alloc(' + alloc + ')\n        dma.load(q, ' + alloc + ').wait()', 1)
        return _c(OS, 'x.mgc', s)

    def test_rank_limit_from_capabilities(self):
        with self.assertRaises(MgcError) as cm:
            self._x3('X3[tile_h, 0:2, 0:t_size]')
        self.assertIn('at most 2-D', str(cm.exception))

    def test_3d_idma_is_a_table_change(self):
        caps = devices.IdmaCaps(max_rank=3, l1_strided=False,
                                functions={1: 'mg_idma_memcpy_1d', 2: 'mg_idma_memcpy_2d', 3: 'mg_idma_memcpy_3d'})
        with mock.patch.object(devices, 'IDMA', caps):
            c = self._x3('X3[tile_h, 0:2, 0:t_size]')
        self.assertIn('mg_idma_memcpy_3d(', c)
        self.assertIn('uint32_t std2_q = ', c)

    def test_contiguous_3d_is_1d(self):
        c = self._x3('X3[tile_h, 0:4, :]')
        self.assertIn('uint32_t len_q = tile_h * 4 * (N_SIZE / 4) * 2;', c)
        self.assertIn('(tile_h_max * y_id * 4 * (N_SIZE / 4) * 2)', c)

    def test_indexed_3d_is_2d(self):
        c = self._x3('X3[tile_h, 1, :]')
        self.assertIn('uint32_t len_q = N_SIZE / 4 * 2;', c)
        self.assertIn('uint32_t std_q = 4 * (N_SIZE / 4) * 2;', c)

    def test_new_hwpe_is_a_descriptor(self):
        acc = devices.Hwpe(
            name='neureka', ctrl='&neureka_ctrl', queue_depth=2,
            jobs={'scale': devices.HwpeJob(operands=(('a', 'in', 2), ('b', 'out', 2)),
                                           params=(('uint32_t', 'a.size'),),
                                           constraints=(('a.shape[0]', 'b.shape[0]'),
                                                        ('a.shape[1]', 'b.shape[1]')))},
            fn={'oneshot': 'mg_neureka_{job}', 'wait': 'mg_neureka_wait'})
        hw = dict(devices.HWPES, neureka=acc)
        src = _read(L1K, 'mm_os_l1k.mgc').replace('copy(x[i], x_raw[i])', 'neureka.scale(x_raw[i], x[i])')
        with mock.patch.dict(devices.HWPES, hw):
            c = _c(L1K, 'x.mgc', src)
            self.assertIn('mg_neureka_scale(&neureka_ctrl,', c)
            self.assertIn('(uint32_t)(tile_h * t_size)', c)
            self.assertIn('mg_neureka_wait(&eu_ctrl, WAIT_MODE, &neureka_evt);', c)
            bad = src.replace('neureka.scale(x_raw[i], x[i])', 'neureka.scale(x_raw[i], w[i])')
            with self.assertRaises(MgcError) as cm:
                _c(L1K, 'x.mgc', bad)
            self.assertIn('neureka.scale shapes do not match', str(cm.exception))


class Errors(unittest.TestCase):

    def assertError(self, old, new, msg, d=OS, src='mm_os_explicit.mgc'):
        s = _read(d, src)
        self.assertIn(old, s)
        with self.assertRaises(MgcError) as cm:
            _c(d, 'x.mgc', s.replace(old, new, 1))
        self.assertIn(msg, str(cm.exception))

    def test_strided_slice(self):
        self.assertError('X[tile_h, 0:t_size], depth=2', 'X[tile_h, 0:t_size:2], depth=2', 'unit step')

    def test_l1_to_l1(self):
        self.assertError('ey = dma.load(y, Y[tile_h, tile_w])', 'ey = dma.load(y, x[0])', 'L1->L1')

    def test_dma_shape_mismatch(self):
        self.assertError('ex = dma.load(x[0], X[tile_h, 0:t_size])',
                         'ex = dma.load(x[0], X[tile_h, 0:2 * t_size])', 'shape mismatch')

    def test_gemm_shape_mismatch(self):
        self.assertError('redmule.enqueue(x[0], w[0], y,', 'redmule.enqueue(w[0], x[0], y,', 'shapes do not match')

    def test_u8_overflow(self):
        self.assertError('timeslots: u8 = N_TIMESLOTS', 'timeslots: u8 = 4 * N', 'does not fit')

    def test_cores_reserved(self):
        self.assertError('for z in range(N_ITERATIONS):', 'for z in cores():', 'reserved')

    def test_nested_tiles(self):
        self.assertError('for z in range(N_ITERATIONS):', 'for z, zz in tiles():', 'outermost')

    def test_unwaited_event_reuse(self):
        self.assertError('            ex.wait()\n            ew.wait()\n            ey.wait()\n',
                         '            ew.wait()\n            ey.wait()\n'
                         '            ex = dma.load(x[1], X[tile_h, t_size:2 * t_size])\n',
                         'was not waited')

    def test_wait_never_issued(self):
        self.assertError('            ex.wait()\n            ew.wait()\n            ey.wait()\n',
                         '            ex.wait()\n            ex.wait()\n            ew.wait()\n            ey.wait()\n',
                         'never issued')

    def test_bad_slot_offset(self):
        self.assertError('ex = dma.load(x[i + 1],', 'ex = dma.load(x[i + 3],', '|k| < 2')

    def test_after_is_gone(self):
        self.assertError('redmule.gemm(x[i], w[i], y)', 'redmule.gemm(x[i], w[i], y, after=(ey,))',
                         'inferred', src='mm_os.mgc')

    def test_remote_load_rejected(self):
        self.assertError('dma.load(x[pt], X[pt * t_size:(pt + 1) * t_size, tile_h])',
                         'dma.load(x[pt], x.on(1, 0)[pt])', 'L1->L1', d=WS, src='mm_ws.mgc')

    def test_unknown_size(self):
        self.assertError('sizes("M_SIZE", "N_SIZE", "K_SIZE")', 'sizes("M_SIZE", "N_SIZE", "Q_SIZE")',
                         'not #defined')


if __name__ == '__main__':
    unittest.main()
