# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Yvan Tortorella <yvan.tortorella@unibo.it>
#

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import argparse
import os
from tqdm import tqdm

# COMPUTE:
# Z[m_size, k_size] = ( X[m_size, n_size] max W[n_size, k_size] ) + Y[m_size, k_size]

#Visualize data with more precision
torch.set_printoptions(precision=10, sci_mode=False)

parser = argparse.ArgumentParser("mm Operation Test")
parser.add_argument( '--m_size', type=int, default=3 )
parser.add_argument( '--n_size', type=int, default=3 )
parser.add_argument( '--k_size', type=int, default=3 )
parser.add_argument( '--inc_dir', type=str, default='include')
args = parser.parse_args()

# Network parameters
m_size = args.m_size
n_size = args.n_size
k_size = args.k_size

# We want to perform a GEMM, of the kind Z = Y + X*W
# Test Matrices
X = torch.rand(m_size, n_size)
W = torch.rand(n_size, k_size)
Y = torch.rand(m_size, k_size)
Z = torch.rand(m_size, k_size)

print("\nInput Data: ")
print("\nX is: ", X, X.shape, X.dtype)

print("\nW is: ", W, W.shape, W.dtype)

print("\nY is: ", Y, Y.shape, Y.dtype)

print("\nComputing bit-true matrix multiplication..")

import numpy as np

def bittrue_fma(a, x, b):
    # Simulate FP16 FMA with intermediate rounding
    a_fp32 = np.float16(a).astype(np.float64)
    x_fp32 = np.float16(x).astype(np.float64)
    b_fp32 = np.float16(b).astype(np.float64)
    result = a_fp32 * x_fp32 + b_fp32
    return np.float16(result).astype(np.float64)

def matrix_multiply_with_bittrue_fma(X, W, Y):
    M, K = X.shape
    K2, N = W.shape
    assert K == K2, "Inner dimensions must match"

    Z = np.zeros((M, N), dtype=np.float64)

    for m in tqdm(range(M)):
        for n in range(N):
            acc = Y[m, n].astype(np.float64)  # Start with Y as accumulator
            for k in range(K):
                acc = bittrue_fma(X[m, k], W[k, n], acc)
            Z[m, n] = acc
    Z = Z.astype(np.float16)

    return Z
X_np = X.cpu().numpy()
W_np = W.cpu().numpy()
Y_np = Y.cpu().numpy()
Z = matrix_multiply_with_bittrue_fma(X_np, W_np, Y_np)
Z = torch.from_numpy(Z).to(dtype=torch.float16)

print("\nZ is: ", Z, Z.shape, Z.dtype)

print("\n\n")

in_rows  = str(m_size)
in_cols  = str(n_size)
out_cols = str(k_size)
x_dim    = str(m_size*n_size)
w_dim    = str(n_size*k_size)
y_dim    = str(m_size*k_size)
z_dim    = str(m_size*k_size)
out_int  = str(int(m_size*k_size/2))

# ------------------------------------------------------------------------------------#
#                             Header file generation                                  #
# ------------------------------------------------------------------------------------#

# Create include directory if it doesn't exist
inc_path = args.inc_dir
if not os.path.exists(inc_path):
    os.makedirs(inc_path)

# Generate single test.h file
f = open(os.path.join(inc_path, 'test.h'), "w")

# Write header guard and comments
f.write('// Copyright 2026 ETH Zurich, University of Bologna and Fondazione Chips-IT.\n')
f.write('// Licensed under the Apache License, Version 2.0, see LICENSE for details.\n')
f.write('// SPDX-License-Identifier: Apache-2.0\n')
f.write('// Generated by gen_golden.py (M='+in_rows+', N='+in_cols+', P='+out_cols+', seed=42)\n')
f.write('//\n')
f.write('// GEMM with bias: Z['+in_rows+'x'+out_cols+'] = X['+in_rows+'x'+in_cols+'] @ W['+in_cols+'x'+out_cols+'] + Y['+in_rows+'x'+out_cols+']\n')
f.write('\n')
f.write('#ifndef _TEST_MM_OS_INCLUDE_GUARD_\n')
f.write('#define _TEST_MM_OS_INCLUDE_GUARD_\n')
f.write('\n')

# Write size defines
f.write('#define M_SIZE ('+in_rows+')\n')
f.write('#define N_SIZE ('+in_cols+')\n')
f.write('#define K_SIZE ('+out_cols+')\n')
f.write('\n')

# Write x_inp array
f.write('uint16_t x_inp       [M_SIZE * N_SIZE] = {\n')
for i in range(m_size):
    for j in range(n_size):
        x_bin = bin(np.float16(X[i][j]).view('H'))[2:].zfill(16)
        x_hex = hex(int(x_bin, 2))[2:]
        if (i == m_size - 1 and j == n_size - 1):
            f.write('0x'+x_hex)
        else:
            f.write('0x'+x_hex+', ')
        if (j == n_size - 1):
            f.write('\n')
f.write('};\n')
f.write('\n')

# Write w_inp array
f.write('uint16_t w_inp       [N_SIZE * K_SIZE] = {\n')
for i in range(n_size):
    for j in range(k_size):
        w_bin = bin(np.float16(W[i][j]).view('H'))[2:].zfill(16)
        w_hex = hex(int(w_bin, 2))[2:]
        if (i == n_size - 1 and j == k_size - 1):
            f.write('0x'+w_hex)
        else:
            f.write('0x'+w_hex+', ')
        if (j == k_size - 1):
            f.write('\n')
f.write('};\n')
f.write('\n')

# Write y_inp array
f.write('uint16_t y_inp       [M_SIZE * K_SIZE] = {\n')
for i in range(m_size):
    for j in range(k_size):
        y_bin = bin(np.float16(Y[i][j]).view('H'))[2:].zfill(16)
        y_hex = hex(int(y_bin, 2))[2:]
        if (i == m_size - 1 and j == k_size - 1):
            f.write('0x'+y_hex)
        else:
            f.write('0x'+y_hex+', ')
        if (j == k_size - 1):
            f.write('\n')
f.write('};\n')
f.write('\n')

# Write z_out array
f.write('uint16_t z_out       [M_SIZE * K_SIZE] = {\n')
for i in range(m_size):
    for j in range(k_size):
        z_bin = bin(np.float16(Z[i][j]).view('H'))[2:].zfill(16)
        z_hex = hex(int(z_bin, 2))[2:]
        if (i == m_size - 1 and j == k_size - 1):
            f.write('0x'+z_hex)
        else:
            f.write('0x'+z_hex+', ')
        if (j == k_size - 1):
            f.write('\n')
f.write('};\n')
f.write('\n')

# Write closing header guard
f.write('#endif //_TEST_GEMM_INCLUDE_GUARD_\n')
f.close()
