#!/usr/bin/env python3
"""
Generate test.h for the GEMM chain test.
Computes a 4-GEMM chain with task-level parallelism:
  Phase 1 (parallel): R1 = M1 @ M2,  R2 = M3 @ M4
  Phase 2:            R3 = R1 @ R2
  Phase 3:            O  = R3 @ M5

All GEMMs use fp16 throughout (inputs, accumulation, outputs).

Usage:
  python3 tests/magia/mesh/gemm/gen_golden.py
  python3 tests/magia/mesh/gemm/gen_golden.py --dim-a 8 --dim-b 12 --dim-c 16 --dim-d 8 --dim-e 8 --dim-f 12
"""

import argparse
import os
import sys

import torch

DEFAULT_OUTPUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "include", "test.h"
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate test.h for the GEMM chain test."
    )
    parser.add_argument("--dim-a", type=int, default=4, help="Dimension A (default: 4)")
    parser.add_argument("--dim-b", type=int, default=8, help="Dimension B (default: 8)")
    parser.add_argument("--dim-c", type=int, default=16, help="Dimension C (default: 16)")
    parser.add_argument("--dim-d", type=int, default=32, help="Dimension D (default: 32)")
    parser.add_argument("--dim-e", type=int, default=64, help="Dimension E (default: 64)")
    parser.add_argument("--dim-f", type=int, default=128, help="Dimension F (default: 128)")
    parser.add_argument("--seed", type=int, default=42, help="RNG seed (default: 42)")
    parser.add_argument("--dtype", type=str, default="fp16",
                        choices=["fp16", "bfloat16"],
                        help="Input data type (default: fp16)")
    parser.add_argument("-o", "--output", type=str, default=DEFAULT_OUTPUT,
                        help=f"Output path (default: {DEFAULT_OUTPUT})")
    return parser.parse_args()


def validate_params(a, b, c, d, e, f):
    errors = []
    for name, val in [("A", a), ("B", b), ("C", c), ("D", d), ("E", e), ("F", f)]:
        if val % 4 != 0:
            errors.append(
                f"DIM_{name} ({val}) must be divisible by 4 (RedMule PE-array alignment).\n"
                f"  Hint: try --dim-{name.lower()} {4 * ((val // 4) + 1)}"
            )
    if errors:
        print("ERROR: Invalid parameters:\n", file=sys.stderr)
        for err in errors:
            print(f"  - {err}\n", file=sys.stderr)
        sys.exit(1)


def get_device():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    if device.type == 'cuda':
        print(f"Using GPU: {torch.cuda.get_device_name(device)} (true fp16 accumulation)")
    else:
        print("WARNING: CUDA not available, falling back to CPU. "
              "CPU fp16 matmul may use fp32 accumulation internally.",
              file=sys.stderr)
    return device


def generate_inputs(a, b, c, d, e, f, seed, device, dtype=torch.float16):
    gen = torch.Generator(device=device).manual_seed(seed)
    m1 = torch.empty((a, b), dtype=dtype, device=device).uniform_(-0.5, 0.5, generator=gen)
    m2 = torch.empty((b, c), dtype=dtype, device=device).uniform_(-0.5, 0.5, generator=gen)
    m3 = torch.empty((c, d), dtype=dtype, device=device).uniform_(-0.5, 0.5, generator=gen)
    m4 = torch.empty((d, e), dtype=dtype, device=device).uniform_(-0.5, 0.5, generator=gen)
    m5 = torch.empty((e, f), dtype=dtype, device=device).uniform_(-0.5, 0.5, generator=gen)
    return m1, m2, m3, m4, m5


def compute_golden(m1, m2, m3, m4, m5):
    """Compute golden outputs using matmul in the same dtype as the inputs."""
    # GEMM1: R1 = M1 @ M2
    r1 = m1 @ m2
    # GEMM2: R2 = M3 @ M4
    r2 = m3 @ m4
    # GEMM3: R3 = R1 @ R2
    r3 = r1 @ r2
    # GEMM4: O = R3 @ M5
    o = r3 @ m5
    return r1, r2, r3, o


def format_array(arr, name, size_expr=None):
    """Format a torch tensor as a C float16 array declaration."""
    if size_expr:
        decl = f'extern float16 {name:<12s}[{size_expr}] = {{'
    else:
        decl = f'extern float16 {name:<12s}[] = {{'

    vals = []
    for v in arr.flatten().tolist():
        vals.append(f'{v}f')

    lines = [decl]
    for i in range(0, len(vals), 8):
        chunk = ', '.join(vals[i:i+8])
        if i + 8 < len(vals):
            chunk += ','
        lines.append(chunk)
    lines.append('};')
    return '\n'.join(lines)


def write_test_h(output_path, dims, seed, m1, m2, m3, m4, m5, r1, r2, r3, o):
    a, b, c, d, e, f = dims
    parts = []

    parts.append(f"""\
// Generated by gen_golden.py (A={a}, B={b}, C={c}, D={d}, E={e}, F={f}, seed={seed})
//
// GEMM chain:
//   Phase 1: R1[{a}x{c}] = M1[{a}x{b}] @ M2[{b}x{c}]
//            R2[{c}x{e}] = M3[{c}x{d}] @ M4[{d}x{e}]
//   Phase 2: R3[{a}x{e}] = R1[{a}x{c}] @ R2[{c}x{e}]
//   Phase 3: O [{a}x{f}] = R3[{a}x{e}] @ M5[{e}x{f}]""")

    parts.append("""
#ifndef _TEST_GEMM_INCLUDE_GUARD_
#define _TEST_GEMM_INCLUDE_GUARD_""")

    parts.append(f"""
#define DIM_A ({a})
#define DIM_B ({b})
#define DIM_C ({c})
#define DIM_D ({d})
#define DIM_E ({e})
#define DIM_F ({f})
""")

    # Input arrays
    parts.append(format_array(m1.flatten(), 'm1_inp'))
    parts.append("")
    parts.append(format_array(m2.flatten(), 'm2_inp'))
    parts.append("")
    parts.append(format_array(m3.flatten(), 'm3_inp'))
    parts.append("")
    parts.append(format_array(m4.flatten(), 'm4_inp'))
    parts.append("")
    parts.append(format_array(m5.flatten(), 'm5_inp'))
    parts.append("")

    # Runtime output buffers (written by tiles via DMA)
    parts.append("// Runtime output buffers (written by tiles via DMA)")
    parts.append(f'extern float16 {"r1_out":<12s}[DIM_A * DIM_C] = {{}};')
    parts.append(f'extern float16 {"r2_out":<12s}[DIM_C * DIM_E] = {{}};')
    parts.append(f'extern float16 {"r3_out":<12s}[DIM_A * DIM_E] = {{}};')
    parts.append(f'extern float16 {"o_out":<12s}[DIM_A * DIM_F] = {{}};')
    parts.append("")

    # Golden arrays
    parts.append("// Golden arrays for validation")
    parts.append(format_array(o.flatten(), 'o_golden'))
    parts.append("")
    parts.append(format_array(r1.flatten(), 'r1_golden', 'DIM_A * DIM_C'))
    parts.append("")
    parts.append(format_array(r2.flatten(), 'r2_golden', 'DIM_C * DIM_E'))
    parts.append("")
    parts.append(format_array(r3.flatten(), 'r3_golden', 'DIM_A * DIM_E'))

    parts.append("\n#endif //_TEST_GEMM_INCLUDE_GUARD_")
    parts.append("")

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, 'w') as fh:
        fh.write('\n'.join(parts))


def main():
    args = parse_args()
    a, b, c, d, e, f = args.dim_a, args.dim_b, args.dim_c, args.dim_d, args.dim_e, args.dim_f

    validate_params(a, b, c, d, e, f)

    print(f"Generating test.h: A={a}, B={b}, C={c}, D={d}, E={e}, F={f}, seed={args.seed}")
    print(f"  GEMM1: M1[{a}x{b}] @ M2[{b}x{c}] -> R1[{a}x{c}]")
    print(f"  GEMM2: M3[{c}x{d}] @ M4[{d}x{e}] -> R2[{c}x{e}]")
    print(f"  GEMM3: R1[{a}x{c}] @ R2[{c}x{e}] -> R3[{a}x{e}]")
    print(f"  GEMM4: R3[{a}x{e}] @ M5[{e}x{f}] -> O[{a}x{f}]")

    device = get_device()
    dtype = torch.bfloat16 if args.dtype == "bfloat16" else torch.float16
    print(f"Input dtype: {dtype}")
    m1, m2, m3, m4, m5 = generate_inputs(a, b, c, d, e, f, args.seed, device, dtype)
    r1, r2, r3, o = compute_golden(m1, m2, m3, m4, m5)

    print(f"\nR1 range: [{float(r1.min()):.4f}, {float(r1.max()):.4f}]")
    print(f"R2 range: [{float(r2.min()):.4f}, {float(r2.max()):.4f}]")
    print(f"R3 range: [{float(r3.min()):.4f}, {float(r3.max()):.4f}]")
    print(f"O  range: [{float(o.min()):.4f}, {float(o.max()):.4f}]")

    write_test_h(args.output, (a, b, c, d, e, f), args.seed,
                 m1, m2, m3, m4, m5, r1, r2, r3, o)

    print(f"\nWrote {args.output}:")
    print(f"  m1_inp:    {a*b} values ({a}x{b})")
    print(f"  m2_inp:    {b*c} values ({b}x{c})")
    print(f"  m3_inp:    {c*d} values ({c}x{d})")
    print(f"  m4_inp:    {d*e} values ({d}x{e})")
    print(f"  m5_inp:    {e*f} values ({e}x{f})")
    print(f"  o_golden:  {a*f} values ({a}x{f})")
    print(f"  r1_golden: {a*c} values ({a}x{c})")
    print(f"  r2_golden: {c*e} values ({c}x{e})")
    print(f"  r3_golden: {a*e} values ({a}x{e})")


if __name__ == '__main__':
    main()
